# Generated by Django 3.1.5 on 2021-03-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_auto_20210301_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='antiguedad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='metros',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='titulo',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
