# Generated by Django 3.1.5 on 2021-03-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_inmueble_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.CharField(blank=True, default='Consultar', max_length=20, null=True),
        ),
    ]
