# Generated by Django 3.1.5 on 2021-03-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_auto_20210303_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.CharField(default='Consultar', max_length=20),
        ),
    ]
