# Generated by Django 3.1.5 on 2021-03-03 04:06

from django.db import migrations, models
import inmuebles.models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0006_auto_20210303_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(upload_to='inmueble', null=True, blank=True),
        ),
    ]
