# Generated by Django 3.2.4 on 2021-07-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0009_auto_20210304_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='destacado',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen4',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen5',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen6',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen7',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen8',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen9',
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inmueble')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.inmueble')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imágenes',
            },
        ),
    ]
