# Generated by Django 3.2.4 on 2021-07-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0010_auto_20210719_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenes',
            options={'verbose_name': 'imagen', 'verbose_name_plural': 'imagenes'},
        ),
    ]
