# Generated by Django 3.2.4 on 2021-07-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0012_imagenes_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default=2, upload_to='inmueble'),
            preserve_default=False,
        ),
    ]
