# Generated by Django 3.2.4 on 2021-07-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0014_alter_imagenes_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='direccion',
            field=models.CharField(default='Referencia', max_length=50),
        ),
    ]
