# Generated by Django 3.1.5 on 2021-02-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='create',
            new_name='created',
        ),
    ]
